Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/homebrew/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/homebrew/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import SimpleITK as sitk

import numpy as np
import pandas as pd 
import scipy.ndimage as ndimage
import seaborn as sns
import scipy.stats as scipy
from sklearn.decomposition import PCA

import os

%matplotlib widget

import matplotlib as mpl
import matplotlib.pyplot as plt
from folder_root.BioArchi.bioarchi import *

from ipywidgets import interact, fixed

print(sitk.Version())


mpl.rc('figure', max_open_warning = 0)

label_nuclei_path = "output/BAL_final2/label_nuclei_cleaned.nii.gz"
label_cells_with_complete_nuclei_path = "output/BAL_final2/label_cells_with_complete_nuclei.nii.gz"
label_cells_complete_cleaned_path = "output/BAL_final2/label_cells_complete_cleaned.nii.gz"

#background_path = "/Users/florianrobert/MEGAsync/Th√®se/Donnees_SEM_2022/Task001_Nuclei/imagesTr/BAL_0000.nii.gz"

data_path = "output/BAL_final2/all_data_BAL.csv"
contour_path = "output/BAL_final2/contour_cells.nii.gz"
vessel_path = "output/BAL_final2/Vessel.nii.gz"
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
[0;32m/var/folders/53/3cyw1xrs71n9jsyg9ztzb5lw0000gn/T/ipykernel_2394/3194408379.py[0m in [0;36m<module>[0;34m[0m
[1;32m     14[0m [0;32mimport[0m [0mmatplotlib[0m [0;32mas[0m [0mmpl[0m[0;34m[0m[0;34m[0m[0m
[1;32m     15[0m [0;32mimport[0m [0mmatplotlib[0m[0;34m.[0m[0mpyplot[0m [0;32mas[0m [0mplt[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 16[0;31m [0;32mfrom[0m [0mfolder_root[0m[0;34m.[0m[0mBioArchi[0m[0;34m.[0m[0mbioarchi[0m [0;32mimport[0m [0;34m*[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     17[0m [0;34m[0m[0m
[1;32m     18[0m [0;32mfrom[0m [0mipywidgets[0m [0;32mimport[0m [0minteract[0m[0;34m,[0m [0mfixed[0m[0;34m[0m[0;34m[0m[0m

[0;31mModuleNotFoundError[0m: No module named 'folder_root'
ModuleNotFoundError: No module named 'folder_root'

